window.PROJECT_ORDER = [
  'onboarding',
  'custom-stickers',
  'automations',
  'ask-ai',
  'customer-insights',
  'navigation',
  'visualisations',
  'developer-tools',
  'design-systems',
];

window.PROJECTS = {
  onboarding: {
    title: 'Onboarding',
    company: 'Miro',
    year: '2026',
    headline: 'The first five minutes decide everything.',
    headlineAccent: 'everything',
    team: 'Miro · Growth Adoption',
    intro: 'First-run experiences that orient new users and set them up for success.',
    paragraphs: [
      'We mapped key activation moments — creating a first board, inviting a teammate, and discovering core tools — then designed lightweight prompts and progressive disclosure around them.',
      'Onboarding work centred on helping people understand what Miro is for and how to get value from it in their first session. The challenge was guiding without overwhelming.',
      'The approach prioritised momentum: fewer steps to a meaningful outcome, with clear off-ramps for users who wanted to explore on their own.',
    ],
    quote: 'I understood exactly what to do within the first minute.',
    quoteBy: 'Customer feedback',
  },
  'custom-stickers': {
    title: 'Custom Stickers',
    company: 'Miro',
    year: '2026',
    headline: 'Unblocking Personal\nExpression with Gen AI',
    headlineAccent: 'Expression',
    team: 'Miro · Growth Adoption',
    images: [
      'images/custom-stickers-hero.png',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    polaroids: [
      { src: 'images/sticker-photo-1.jpg', r: -5 },
      { src: 'images/sticker-photo-2.jpg', r: 4 },
    ],
    intro: 'A text-to-sticker generative AI tool built into Miro’s stickers panel.',
    paragraphs: [
      'Miro’s library of emojis and static stickers was popular but finite. In retrospectives and design sprints, teams kept running out of ways to react to a specific idea, an inside joke, or anything too niche for a stock icon. Keeping the set stocked was our job, and it didn’t scale — every addition meant more design and production work for a library that could never cover everything.',
      'So we built Custom Stickers, a text-to-sticker generator that sits inside the panel people already use. Type “taco wearing sunglasses” and you get transparent, on-brand options in seconds; the interface applies the outlines and styling behind the scenes, so a few words are enough to get a usable result. It turned into a genuine engagement driver — during live workshops it gamified the whole session, and teams started building their own visual shorthand as they went.',
      'We integrated the generator directly into the existing stickers panel, so users could type a simple phrase — “taco wearing sunglasses” — and get high-quality, transparent sticker options in seconds. Behind the scenes, the interface automatically applied visual parameters like bold outlines and sticker styles, so even basic text inputs produced consistent, high-fidelity results.',
      'Custom Stickers became a major engagement driver. We hosted a live, in-person printing experience for these custom stickers, which proved to be a huge crowd pleaser at our Canvas26 event. During live workshops it naturally gamified collaboration, causing an immediate spike in user-to-user interactions. By lowering the barrier to creation, we gave teams a way to co-create their own visual language in real time — dramatically increasing session energy and proving that generative AI can be as much about delight and connection as it is about productivity.',
    ],
    quote: 'What seems like a simple feature to us can be a profound tool for self-validation to someone else; great ideas always transcend their original purpose.',
    quoteBy: 'Customer feedback',
  },
  automations: {
    title: 'Automations',
    company: 'Miro',
    year: '2025',
    headline: 'Designing Proactive Customer Insights Automations',
    headlineAccent: 'Proactive',
    team: 'Miro · Insights',
    intro: 'Turning manual querying into scheduled, recurring insight workflows that come to you.',
    images: [
      'images/automations-hero.png',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    paragraphs: [
      'Product managers and researchers liked the insights but were tired of logging in every week to re-run the same handful of searches — feature requests from sales calls, complaints about the last release. Query fatigue set in, and it meant the product only worked on the weeks somebody remembered to visit it.',
      'Automations turns those repeat searches into scheduled reports, delivered wherever a team already works: Slack, email or in-product. We reduced setup to a three-step trigger, action and destination that takes about a minute, then spent the time with engineering on making the scheduling and delivery dull and reliable. It saved researchers hours of manual reporting a month, and because the reports land in shared channels, people without accounts started seeing the value too.',
      'We defined the automation framework, simplifying complex logic into a straightforward “Trigger, Action, Destination” flow that any user could configure in under a minute. Rather than keeping users locked in our app, we designed for the existing ecosystem — mapping a multi-channel delivery experience so insights could meet teams where they collaborate, specifically Slack and email. Throughout, we worked closely with engineering to balance technical feasibility with experience, keeping scheduling and delivery reliable without over-complicating the initial release.',
      'By automating the delivery of recurring insights, we integrated the product into the weekly routines of entire product squads. Bringing insights directly into Slack saved researchers hours of manual reporting every month, and it organically boosted visibility across the company — bringing team members who didn’t even have active accounts face-to-face with our value.',
    ],
    quote: 'Automations help keep our entire team updated on what our customers are saying, straight in our Slack channels.',
    quoteBy: 'Customer feedback',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Kosta Bolgov', photo: 'images/team-kosta.png' },
      { name: 'Roana Bilia', photo: 'images/team-roana.jpg' },
      { name: 'Cody Mathison', photo: 'images/team-cody.png' },
      { name: 'Ophir Horowitz', photo: 'images/team-ophir.jpg' },
    ],
  },
  'ask-ai': {
    title: 'Ask Insights',
    company: 'Miro',
    year: '2025',
    headline: 'Instant Answers to Complex Customer Questions',
    headlineAccent: 'Answers',
    team: 'Miro · Insights',
    intro: 'An AI chat companion that turns a repository of customer feedback into instant, cited answers.',
    images: [
      'images/ask-ai-hero.png',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Kosta Bolgov', photo: 'images/team-kosta.png' },
      { name: 'Brittney Reyes', photo: 'images/team-brittney.jpg' },
      { name: 'Cody Mathison', photo: 'images/team-cody.png' },
      { name: 'Frak Lopez', photo: 'images/team-frank.jpg' },
    ],
    paragraphs: [
      'Research and product teams had years of customer conversation on file — sales calls, support logs, interviews — and no practical way to read it. Answering something as ordinary as “what are people saying about onboarding?” meant hours of searching and synthesising, so more often than not the question went unasked.',
      'Ask Insights puts that question to the whole archive in plain English and answers it in seconds, with citations. Trust was the hard part, so every claim links back to the exact moment in the original call — you can read the sentence it came from. A set of suggested prompts, picked for your role, makes the empty chat box less daunting, and follow-ups let you drill from a broad question down to a specific detail. Because people could check the sources, they believed the answers, and it became the tool teams opened before sprint planning.',
      'Trust is the biggest hurdle with AI, so we structured the chat interface to heavily prioritise inline citations and source links — users can click straight through to the exact snippet of the original customer call or transcript to verify a response. To make a blank chat box less intimidating, we designed a zero-state onboarding with suggested, high-value prompts based on the user’s role, guiding them to value on their very first interaction. We also refined the iterative search flow to support continuous follow-ups, letting users drill down from a broad query — “What are our top customer pain points?” — to a specific detail like “Tell me more about the payment errors they mentioned.”',
      'Ask Insights fundamentally changed how product decisions get made by democratising access to customer data. By shrinking the research loop from days to seconds, we empowered product managers, marketers, and developers to self-serve insights autonomously. Clear citations meant the team actually trusted the AI’s outputs, making the feature the go-to tool for pre-sprint planning and roadmap validation.',
    ],
    quote: 'It’s amazing how quickly we can surface customer feedback that before took such mental effort to gather.',
    quoteBy: 'Product manager at Miro',
  },
  'customer-insights': {
    title: 'Canvas Insights',
    company: 'Miro',
    year: '2024',
    headline: 'Bringing Rich Customer\nData to the Canvas',
    headlineAccent: 'Canvas',
    team: 'Miro · Insights',
    intro: 'On-canvas insight cards that bring rich customer data into Miro boards.',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Wiz', photo: 'images/team-wiz.jpg' },
      { name: 'Frak Lopez', photo: 'images/team-frank.jpg' },
      { break: true },
      { name: 'Brittney Reyes', photo: 'images/team-brittney.jpg' },
      { name: 'Mor Sela', photo: 'images/team-mor.jpg' },
    ],
    images: [
      'images/canvas-insights-hero.png',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    paragraphs: [
      'Good customer insight tends to stay wherever it was collected. Teams running workshops in Miro were copy-pasting findings across as plain sticky notes, which stripped out the quotes, metadata and context that made them worth citing in the first place — leaving a workshop full of claims nobody could trace.',
      'Insight cards bring the source of truth onto the canvas. They restructure themselves depending on where you drop them — compact inside a table, spanning a kanban column, opening out to the full customer quote when they stand alone — so they fit whatever structure a team already works in. Researchers can import and tag; everyone else can skim. Either way the card links back to the original feedback, so a conclusion drawn in a workshop can be traced to something a customer actually said.',
      'We designed an adaptive component system — “Insight Cards” that restructure based on placement, fitting neatly inside compact tables, spanning across kanban columns, or expanding to show full customer quotes when displayed solo on the canvas. We built for diverse personas so both creators and consumers were served: researchers could easily import and tag data, while designers and PMs could digest key takeaways at a glance without being overwhelmed by density. And we optimised spatial usability, refining how the cards behaved in Miro’s canvas — smooth drag-and-drop, sensible resizing constraints, and intuitive linking back to the original feedback sources.',
      'Canvas Insights turned static data into an active participant in collaborative workshops. By bringing rich, context-heavy insight cards directly onto the canvas, we eliminated the friction of context-switching between Miro and external databases. This greatly improved how teams mapped product opportunities to real user problems, making roadmapping and prioritisation sessions significantly more data-driven and cohesive.',
    ],
    quote: 'This helps us make decisions based on data we can trust, and gives stakeholders visibility into results without constant back and forth among teams.',
    quoteBy: 'Customer feedback',
  },
  navigation: {
    title: 'Navigation',
    company: 'Cashbook',
    year: '2024',
    headline: 'Designing a Scalable Foundation for Multi-Product Growth',
    headlineAccent: 'Scalable',
    team: 'Cashbook',
    intro: 'Scalable navigation and information architecture for Cashbook’s accounting platform.',
    images: [
      'images/navigation-hero.png?v=3',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    teamMembers: [],
    paragraphs: [
      'Cashbook’s interface was straining under its own growth. The navigation had no room left for new features, let alone whole new modules, and accountants were paying for it daily — moving between ledgers, reports and settings took more clicks than the work warranted.',
      'We rebuilt the information architecture around tasks rather than the org chart that had shaped it, consolidating deeply nested menus into categories you can scan in one pass. The new framework treats modules as plug-and-play, so a product can be switched on without disturbing the core, and it hands more of the screen back to dense financial tables. Routine reconciliations got shorter, and the team could ship add-ons without redesigning the shell each time.',
      'We restructured the information architecture, auditing and consolidating deeply nested menu items into intuitive, task-oriented categories so accountants could glance at the sidebar and instantly find what they needed. We designed for future modular add-ons with a flexible, nested navigation framework engineered to support “plug-and-play” modules — letting future products be toggled on or off without disrupting the core experience. And we optimised workspace density, maximising screen real estate for complex financial tables and dashboards while keeping navigation accessible and uncluttered.',
      'The redesign decoupled Cashbook’s UI from its legacy limitations. For accountants, the streamlined navigation was an immediate efficiency booster, significantly reducing the clicks and page loads needed to complete routine financial reconciliations. For the business, the modular framework cleared the runway for the product team, enabling them to ship new add-on services and features without costly, recurring design overhauls.',
    ],
  },
  visualisations: {
    title: 'Visualisations',
    company: 'Cashbook',
    year: '2024',
    headline: 'Surfacing What Matters\nin a Sea of Numbers',
    headlineAccent: 'Matters',
    headlineScramble: 'bers',
    team: 'Cashbook',
    intro: 'Visual dashboards that turn dense financial ledgers into at-a-glance insight.',
    images: [
      'images/visualisations-hero.png?v=3',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    teamMembers: [],
    paragraphs: [
      'Managers were making decisions from tables they couldn’t read quickly. Spotting a trend meant working it out by hand or waiting for month-end from their accountant, by which point the moment to act on it had usually passed.',
      'We designed dashboards that pull the few numbers that matter — cash runway, burn rate, outstanding invoices — to the top, as charts built for scanning rather than study. Research decided that list; nothing earned a place for being easy to plot. Each visual is a way in rather than a dead end: hover for detail, or click an odd-looking dip to land in the transactions behind it. A weekly chore became a check-in, and cash flow problems started surfacing while there was still time to do something about them.',
      'We ran user research to pinpoint the most critical “north star” metrics — cash runway, burn rate, outstanding invoices — that managers needed to see the second they logged in. We translated dry, tabular data into clear, interactive charts and trend indicators optimised for rapid scanning and high legibility. And we designed the dashboard as a gateway rather than a dead end, letting users hover for quick details or click a visual anomaly to drill down into the underlying raw transactions.',
      'The visual dashboards completely changed how managers interacted with their financial data, turning a weekly chore of reading spreadsheets into a quick, intuitive visual check-in. By bringing critical trends to the surface, we dramatically cut time-to-insight. Managers could spot cash flow bottlenecks or revenue dips in real time, empowering them to make faster, data-backed decisions with total confidence.',
    ],
  },
  'developer-tools': {
    title: 'Developer Tools',
    company: 'SAP',
    year: '2023',
    headline: 'Designing Native\nDeveloper Experiences',
    headlineAccent: 'Native',
    team: 'SAP · Fiori',
    intro: 'A VS Code extension that makes building SAP apps feel native to the IDE.',
    images: [
      'images/developer-tools-hero.png?v=2',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    paragraphs: [
      'SAP development had always happened inside heavy proprietary tooling, so bringing Fiori Tools to VS Code came with an adoption problem. Developers are protective of their workspace, and anything that reads as an enterprise bolt-on gets uninstalled — however good the underlying utilities are.',
      'So the bar we set was that you shouldn’t be able to tell where Microsoft’s code ends and ours begins. We matched VS Code’s typography, iconography and density, and made every custom element respond to its theming — default light and dark through to community favourites — so nothing came out unreadable when someone switched. Dense app-generation steps turned into sidebars, wizards and command-palette flows that suited keyboard-first habits. With nothing to fight, adoption followed.',
      'We strictly adhered to Microsoft’s design language — matching typography, iconography, and spatial density so the interface felt completely native. We built extensive compatibility with VS Code’s diverse ecosystem of colour themes, from default Dark/Light to community themes, ensuring every custom UI element dynamically adapted and stayed perfectly readable and accessible. And we simplified complex workflows, translating dense SAP application-generation steps into lightweight sidebars, interactive wizards, and command-palette flows that matched the keyboard-first habits of developers.',
      'By respecting the developer’s environment and styling preferences, we turned Fiori Tools into a natural, seamless part of their daily workflow. The native look and feel drastically reduced cognitive load — developers no longer had to mentally switch between differing design philosophies. This user-first approach to developer experience accelerated adoption, making Fiori Tools the preferred, standard way to build modern SAP applications.',
    ],
  },
  'design-systems': {
    title: 'Design Systems',
    company: 'SAP',
    year: '2022',
    headline: 'Scaling a Multi-Theme\nComponent Library',
    headlineAccent: 'Multi-Theme',
    team: 'SAP · Fiori',
    intro: 'A 200+ component Figma system that dynamically supports 10+ VS Code themes.',
    images: [
      'images/sap-fiori-hero.png?v=2',
    ],
    heroAspect: '2842 / 1856',
    heroFit: 'contain',
    paragraphs: [
      'As Fiori Tools grew, the design files came apart. Designers were re-colouring mockups by hand to check how a feature held up in light, dark and high-contrast themes, and engineers couldn’t find the token that matched what they’d been sent.',
      'We rebuilt the Figma library as one source of truth: over 200 components documented from plain buttons up to code-generator wizards, on a variable structure that retints the lot across ten-plus VS Code themes in a click. Naming was mapped to production CSS and JSON alongside the front-end team, which took the guesswork out of handoff. Design once, flip a theme to check contrast, hand it over — QA cycles shortened and the team got its time back for harder problems.',
      'We architected multi-theme variables — a sophisticated colour token and variable structure in Figma that let designers toggle between 10+ themes instantly and watch components dynamically adapt their colours, borders, and contrast. We standardised 200+ components, auditing, rebuilding, and documenting a massive library from simple buttons to complex code-generator wizards, all strictly adhering to both VS Code guidelines and Fiori logic. And we aligned design and engineering tokens, working closely with front-end developers to map Figma properties and variables directly to production CSS and JSON with a unified naming convention that eliminated handoff guesswork.',
      'By standardising the design system, we turned a fragmented workflow into an efficient assembly line. Designers could design a feature once, toggle a theme to verify accessibility, and hand it off to engineering with total confidence. This modernisation drastically cut design handoff times and QA cycles, letting the team focus on solving complex user experience challenges rather than fixing styling inconsistencies.',
    ],
  },
};

// Core team credited on every project page (shown as pills under the quote).
const CORE_TEAM = [
  { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
  { name: 'Mehdi Ghaeini', photo: 'images/team-mehdi.jpg' },
  { name: 'Ben Shih', photo: 'images/team-ben.jpg' },
  { name: 'Iuliia Dutchak', photo: 'images/team-iuliia.jpg' },
  { name: 'Cyan Xiao', photo: 'images/team-cyan.jpg' },
];
// SAP (Fiori) team, shared across the two SAP projects.
const SAP_TEAM = [
  { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
  { name: 'Goran Peuc', photo: 'images/team-goran.jpg' },
  { name: 'Colin Doherty', photo: 'images/team-colin.jpg' },
  { name: 'Christine McCarthy', photo: 'images/team-christine.png' },
  { name: 'Aisling Noone', photo: 'images/team-aisling.jpg' },
];
window.PROJECTS['developer-tools'].teamMembers = SAP_TEAM;
window.PROJECTS['design-systems'].teamMembers = SAP_TEAM;

Object.values(window.PROJECTS).forEach((project) => {
  if (!project.teamMembers) project.teamMembers = CORE_TEAM;
});
