window.PROJECT_ORDER = [
  'onboarding',
  'custom-stickers',
  'automations',
  'ask-ai',
  'customer-insights',
  'navigation',
  'visualisations',
  'developer-tools',
  'design-systems',
];

window.PROJECTS = {
  onboarding: {
    title: 'Onboarding',
    company: 'Miro',
    year: '2026',
    headline: 'The first five minutes decide everything.',
    headlineAccent: 'everything',
    team: 'Miro · Growth Adoption',
    intro: 'First-run experiences that orient new users and set them up for success.',
    paragraphs: [
      'Onboarding work centred on helping people understand what Miro is for and how to get value from it in their first session. The challenge was guiding without overwhelming.',
      'We mapped key activation moments — creating a first board, inviting a teammate, and discovering core tools — then designed lightweight prompts and progressive disclosure around them.',
      'The approach prioritised momentum: fewer steps to a meaningful outcome, with clear off-ramps for users who wanted to explore on their own.',
    ],
    quote: 'I understood exactly what to do within the first minute.',
    quoteBy: 'Customer feedback',
  },
  'custom-stickers': {
    title: 'Custom Stickers',
    company: 'Miro',
    year: '2026',
    headline: 'Unblocking Personal Expression with Generative AI',
    headlineAccent: 'Expression',
    team: 'Miro · Growth Adoption',
    images: [
      'images/custom-stickers-board.png',
      'images/custom-stickers-panel-1.png',
      'images/custom-stickers-panel-2.png',
    ],
    polaroids: [
      { src: 'images/sticker-photo-1.jpg', r: -5 },
      { src: 'images/sticker-photo-2.jpg', r: 4 },
    ],
    heroStickers: [
      'images/sticker-1.png',
      'images/sticker-2.png',
      'images/sticker-3.png',
      'images/sticker-4.png',
      'images/sticker-5.png',
      'images/sticker-6.png',
      'images/sticker-7.png',
      'images/sticker-8.png',
    ],
    intro: 'A text-to-sticker generative AI tool built into Miro’s stickers panel.',
    paragraphs: [
      'Collaboration boards work best when they feel personal and high-energy. We designed Custom Stickers, a generative AI feature for Miro that lets users instantly generate and place custom, styled stickers directly onto the canvas. By translating text prompts into transparent, on-brand graphics, we gave teams a playful, infinitely expressive way to communicate, vote, and react during workshops and brainstorms.',
      'Miro’s existing library of emojis and static stickers was popular, but limited. During highly collaborative sessions like retrospectives or design sprints, users often ran out of relevant ways to visually express specific ideas, inside jokes, or niche reactions. We needed a seamless generative AI experience that let users conjure the exact graphic they wanted on demand, without leaving the canvas or navigating complex prompting tools.',
      'We integrated the generator directly into the existing stickers panel, so users could type a simple phrase — “taco wearing sunglasses” — and get high-quality, transparent sticker options in seconds. Behind the scenes, the interface automatically applied visual parameters like bold outlines and sticker styles, so even basic text inputs produced consistent, high-fidelity results.',
      'Custom Stickers became a major engagement driver. We hosted a live, in-person printing experience for these custom stickers, which proved to be a huge crowd pleaser at our Canvas26 event. During live workshops it naturally gamified collaboration, causing an immediate spike in user-to-user interactions. By lowering the barrier to creation, we gave teams a way to co-create their own visual language in real time — dramatically increasing session energy and proving that generative AI can be as much about delight and connection as it is about productivity.',
    ],
    quote: 'What seems like a simple feature to us can be a profound tool for self-validation to someone else; great ideas always transcend their original purpose.',
    quoteBy: 'Customer feedback',
  },
  automations: {
    title: 'Automations',
    company: 'Miro',
    year: '2025',
    headline: 'Designing Proactive Customer Insights Automations',
    headlineAccent: 'Proactive',
    team: 'Miro · Insights',
    intro: 'Turning manual querying into scheduled, recurring insight workflows that come to you.',
    images: [
      'images/automations-hero.png',
      'images/automations-2.png',
    ],
    paragraphs: [
      'Instead of forcing users to manually dig for recurring customer feedback, we wanted the data to come to them. I designed Automations, a feature that lets teams set up routine, AI-driven insight reports and deliver them directly to where they already work — Slack, email, or in-product. This shifted our product from a manual, reactive search tool to a proactive, habit-forming engine for product teams.',
      'Our users were experiencing “query fatigue.” Product managers and researchers loved our AI insights, but they were tired of logging in every week to run the exact same searches, like tracking feature requests from sales calls. The challenge was to transition the platform from a destination users had to remember to visit into an automated utility that seamlessly integrated into their existing weekly workflows.',
      'I defined the automation framework, simplifying complex logic into a straightforward “Trigger, Action, Destination” flow that any user could configure in under a minute. Rather than keeping users locked in our app, I designed for the existing ecosystem — mapping a multi-channel delivery experience so insights could meet teams where they collaborate, specifically Slack and email. Throughout, I worked closely with engineering to balance technical feasibility with experience, keeping scheduling and delivery reliable without over-complicating the initial release.',
      'By automating the delivery of recurring insights, we integrated the product into the weekly routines of entire product squads. Bringing insights directly into Slack saved researchers hours of manual reporting every month, and it organically boosted visibility across the company — bringing team members who didn’t even have active accounts face-to-face with our value.',
    ],
    quote: 'Automations help keep our entire team updated on what our customers are saying straight in our Slack channels',
    quoteBy: 'Customer feedback',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Kosta Bolgov', photo: 'images/team-kosta.png' },
      { name: 'Roana Bilia', photo: 'images/team-roana.jpg' },
      { name: 'Cody Mathison', photo: 'images/team-cody.png' },
      { name: 'Ophir Horowitz', photo: 'images/team-ophir.jpg' },
    ],
  },
  'ask-ai': {
    title: 'Ask Insights',
    company: 'Miro',
    year: '2025',
    headline: 'Instant Answers to Complex Customer Questions',
    headlineAccent: 'Answers',
    team: 'Miro · Insights',
    intro: 'An AI chat companion that turns a repository of customer feedback into instant, cited answers.',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Kosta Bolgov', photo: 'images/team-kosta.png' },
      { name: 'Brittney Reyes', photo: 'images/team-brittney.jpg' },
      { name: 'Cody Mathison', photo: 'images/team-cody.png' },
      { name: 'Frak Lopez', photo: 'images/team-frank.jpg' },
    ],
    paragraphs: [
      'Sifting through thousands of customer feedback loops to find specific trends can take teams hours, if not days. I designed Ask Insights, an intuitive AI chat companion that lets users query their entire database of customer calls, feedback, and support tickets in plain English. Instead of manually digging through endless transcripts, product teams can simply ask a question and get a synthesized, cited answer in seconds.',
      'User research and product teams were sitting on a goldmine of customer insights, from weekly sales calls to support logs, but the sheer volume made it impossible to digest. When a product manager needed to know “What are users saying about our onboarding experience?” they had to spend hours searching, reading, and synthesizing. We needed a conversational interface that felt as easy as chatting with a colleague, while maintaining the rigor and trust required for serious UX and product decisions.',
      'Trust is the biggest hurdle with AI, so I structured the chat interface to heavily prioritise inline citations and source links — users can click straight through to the exact snippet of the original customer call or transcript to verify a response. To make a blank chat box less intimidating, I designed a zero-state onboarding with suggested, high-value prompts based on the user’s role, guiding them to value on their very first interaction. I also refined the iterative search flow to support continuous follow-ups, letting users drill down from a broad query — “What are our top customer pain points?” — to a specific detail like “Tell me more about the payment errors they mentioned.”',
      'Ask Insights fundamentally changed how product decisions get made by democratising access to customer data. By shrinking the research loop from days to seconds, we empowered product managers, marketers, and developers to self-serve insights autonomously. Clear citations meant the team actually trusted the AI’s outputs, making the feature the go-to tool for pre-sprint planning and roadmap validation.',
    ],
    quote: 'It\'s amazing how quick we can surface customer feedback which before took such mental effort to gather',
    quoteBy: 'Product manager at Miro',
  },
  'customer-insights': {
    title: 'Canvas Insights',
    company: 'Miro',
    year: '2024',
    headline: 'Bringing Rich Customer Data to the Canvas',
    headlineAccent: 'Canvas',
    team: 'Miro · Insights',
    intro: 'On-canvas insight cards that bring rich customer data into Miro boards.',
    teamMembers: [
      { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
      { name: 'Wiz', photo: 'images/team-wiz.jpg' },
      { name: 'Frak Lopez', photo: 'images/team-frank.jpg' },
      { break: true },
      { name: 'Brittney Reyes', photo: 'images/team-brittney.jpg' },
      { name: 'Mor Sela', photo: 'images/team-mor.jpg' },
    ],
    images: [
      'images/canvas-insights-hero.png',
    ],
    heroAspect: '2410 / 1342',
    heroFit: 'contain',
    paragraphs: [
      'UX researchers and product teams often struggle to turn research findings into collaborative action because insights live in static PDFs or isolated databases. I designed Canvas Insights, an on-canvas Miro experience that lets users pull rich, interactive insight card components directly onto their collaborative boards. Engineered to adapt to different use cases and personas, these cards seamlessly integrate into tables, kanban boards, and mind maps, turning raw data into active, collaborative building blocks.',
      'Even when organisations have great customer insights, those insights often stay siloed. When teams ran brainstorming workshops on Miro, they had to manually copy-paste plain-text sticky notes from other tools to represent customer pain points, stripping away critical context, quotes, and metadata. We needed an experience that brought the source of truth directly to the infinite canvas, while keeping the components flexible enough to fit a wide variety of collaborative structures.',
      'I designed an adaptive component system — “Insight Cards” that restructure based on placement, fitting neatly inside compact tables, spanning across kanban columns, or expanding to show full customer quotes when displayed solo on the canvas. I built for diverse personas so both creators and consumers were served: researchers could easily import and tag data, while designers and PMs could digest key takeaways at a glance without being overwhelmed by density. And I optimised spatial usability, refining how the cards behaved in Miro’s canvas — smooth drag-and-drop, sensible resizing constraints, and intuitive linking back to the original feedback sources.',
      'Canvas Insights turned static data into an active participant in collaborative workshops. By bringing rich, context-heavy insight cards directly onto the canvas, we eliminated the friction of context-switching between Miro and external databases. This greatly improved how teams mapped product opportunities to real user problems, making roadmapping and prioritisation sessions significantly more data-driven and cohesive.',
    ],
    quote: 'This helps us make decisions based on data we can trust, and gives stakeholders visibility into results without constant back and forth among teams.',
    quoteBy: 'Customer feedback',
  },
  navigation: {
    title: 'Navigation',
    company: 'Cashbook',
    year: '2024',
    headline: 'Designing a Scalable Foundation for Multi-Product Growth',
    headlineAccent: 'Scalable',
    team: 'Cashbook',
    intro: 'Scalable navigation and information architecture for Cashbook’s accounting platform.',
    images: [
      'images/navigation-hero.png',
    ],
    heroAspect: '1500 / 667',
    heroFit: 'contain',
    teamMembers: [],
    paragraphs: [
      'As a product scales, its navigation must grow with it. I led the redesign of the core navigation interface for Cashbook, a financial management tool for accountants. The goal was twofold: drastically improve daily workflow efficiency so accountants could digest complex financial data faster, while simultaneously restructuring the information architecture to seamlessly accommodate future multi-product add-ons.',
      'The existing Cashbook interface was struggling under the weight of its own growth. The navigation was rigid, leaving little room for new features, let alone entirely new product modules. At the same time, our primary users — accountants — deal with massive volumes of data daily and were experiencing cognitive overload jumping between ledgers, reports, and settings. We needed a layout that felt lighter and faster to navigate today, without breaking when we introduced new tools tomorrow.',
      'I restructured the information architecture, auditing and consolidating deeply nested menu items into intuitive, task-oriented categories so accountants could glance at the sidebar and instantly find what they needed. I designed for future modular add-ons with a flexible, nested navigation framework engineered to support “plug-and-play” modules — letting future products be toggled on or off without disrupting the core experience. And I optimised workspace density, maximising screen real estate for complex financial tables and dashboards while keeping navigation accessible and uncluttered.',
      'The redesign decoupled Cashbook’s UI from its legacy limitations. For accountants, the streamlined navigation was an immediate efficiency booster, significantly reducing the clicks and page loads needed to complete routine financial reconciliations. For the business, the modular framework cleared the runway for the product team, enabling them to ship new add-on services and features without costly, recurring design overhauls.',
    ],
  },
  visualisations: {
    title: 'Visualisations',
    company: 'Cashbook',
    year: '2024',
    headline: 'Surfacing What Matters in a Sea of Numbers',
    headlineAccent: 'Matters',
    headlineScramble: 'bers',
    team: 'Cashbook',
    intro: 'Visual dashboards that turn dense financial ledgers into at-a-glance insight.',
    images: [
      'images/visualisations-hero.png',
    ],
    heroAspect: '1519 / 711',
    heroFit: 'contain',
    teamMembers: [],
    paragraphs: [
      'Accounting software is notoriously dense, often burying crucial business trends under endless rows of spreadsheet data. I designed visual data dashboards that translate raw financial ledgers into high-level, actionable insights for managers. By surfacing key performance indicators like cash flow, revenue trends, and upcoming expenses at a glance, we transformed how business leaders monitor and steer their financial health.',
      'Business managers often struggled to make quick, strategic decisions because their financial data was trapped in massive, overwhelming tables. They were experiencing cognitive fatigue, spending too much time manually calculating trends or waiting for end-of-month reports from their accountants. The challenge was to abstract a highly complex, data-heavy financial ledger into a clean, visual format that was immediately understandable — without losing the depth and accuracy required for business planning.',
      'I ran user research to pinpoint the most critical “north star” metrics — cash runway, burn rate, outstanding invoices — that managers needed to see the second they logged in. I translated dry, tabular data into clear, interactive charts and trend indicators optimised for rapid scanning and high legibility. And I designed the dashboard as a gateway rather than a dead end, letting users hover for quick details or click a visual anomaly to drill down into the underlying raw transactions.',
      'The visual dashboards completely changed how managers interacted with their financial data, turning a weekly chore of reading spreadsheets into a quick, intuitive visual check-in. By bringing critical trends to the surface, we dramatically cut time-to-insight. Managers could spot cash flow bottlenecks or revenue dips in real time, empowering them to make faster, data-backed decisions with total confidence.',
    ],
  },
  'developer-tools': {
    title: 'Developer Tools',
    company: 'SAP',
    year: '2023',
    headline: 'Designing a Native Developer Experience inside VS Code',
    headlineAccent: 'Native',
    team: 'SAP · Fiori',
    intro: 'A VS Code extension that makes building SAP apps feel native to the IDE.',
    images: [
      'images/sap-fiori-hero.png',
    ],
    heroAspect: '1999 / 1033',
    heroFit: 'contain',
    paragraphs: [
      'Building enterprise apps shouldn’t feel like fighting legacy software. I worked on Fiori Tools, a VS Code extension designed to help developers build SAP applications faster and with far less friction. By aligning the UI directly with Microsoft’s native design language and supporting a wide array of IDE colour themes, we brought the SAP development experience into the modern era — making it feel like a natural extension of the developer’s favourite workspace.',
      'Historically, SAP development workflows lived in siloed, heavy proprietary environments. When we brought Fiori Tools to VS Code, we faced a major adoption hurdle: developers are highly protective of their workspaces. If our tools looked or behaved like a clunky enterprise add-on, developers would resist using them. The challenge was to design a complex set of SAP configuration utilities that felt so native to VS Code that developers couldn’t tell where Microsoft’s code ended and SAP’s began.',
      'I strictly adhered to Microsoft’s design language — matching typography, iconography, and spatial density so the interface felt completely native. I built extensive compatibility with VS Code’s diverse ecosystem of colour themes, from default Dark/Light to community themes, ensuring every custom UI element dynamically adapted and stayed perfectly readable and accessible. And I simplified complex workflows, translating dense SAP application-generation steps into lightweight sidebars, interactive wizards, and command-palette flows that matched the keyboard-first habits of developers.',
      'By respecting the developer’s environment and styling preferences, we turned Fiori Tools into a natural, seamless part of their daily workflow. The native look and feel drastically reduced cognitive load — developers no longer had to mentally switch between differing design philosophies. This user-first approach to developer experience accelerated adoption, making Fiori Tools the preferred, standard way to build modern SAP applications.',
    ],
  },
  'design-systems': {
    title: 'Design Systems',
    company: 'SAP',
    year: '2022',
    headline: 'Scaling a Multi-Theme Component Library',
    headlineAccent: 'Multi-Theme',
    team: 'SAP · Fiori',
    intro: 'A 200+ component Figma system that dynamically supports 10+ VS Code themes.',
    images: [
      'images/sap-fiori-hero.png',
    ],
    heroAspect: '1999 / 1033',
    heroFit: 'contain',
    paragraphs: [
      'Designing consistent developer tools at scale requires an ironclad, highly efficient foundation. I led the maintenance and optimisation of the Fiori Tools Figma libraries and design system, establishing a robust framework of over 200 components. By structuring the system to dynamically support more than 10 distinct developer colour themes — from high-contrast light modes to community-favourite dark modes — I bridged the gap between our design files and the production VS Code environment, making it seamless for both designers and engineers to build new features.',
      'As the Fiori Tools feature set expanded, our design files were becoming fragmented. Designers spent too much time manually re-colouring mockups to test how features looked in different VS Code themes like Light, Dark, or High Contrast, and engineers struggled to find the corresponding tokens in production. We needed a single source of truth in Figma that could handle complex, multi-theme logic automatically — without bloating file sizes or slowing down the design team’s daily workflow.',
      'I architected multi-theme variables — a sophisticated colour token and variable structure in Figma that let designers toggle between 10+ themes instantly and watch components dynamically adapt their colours, borders, and contrast. I standardised 200+ components, auditing, rebuilding, and documenting a massive library from simple buttons to complex code-generator wizards, all strictly adhering to both VS Code guidelines and Fiori logic. And I aligned design and engineering tokens, working closely with front-end developers to map Figma properties and variables directly to production CSS and JSON with a unified naming convention that eliminated handoff guesswork.',
      'By standardising the design system, we turned a fragmented workflow into an efficient assembly line. Designers could design a feature once, toggle a theme to verify accessibility, and hand it off to engineering with total confidence. This modernisation drastically cut design handoff times and QA cycles, letting the team focus on solving complex user experience challenges rather than fixing styling inconsistencies.',
    ],
  },
};

// Core team credited on every project page (shown as pills under the quote).
const CORE_TEAM = [
  { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
  { name: 'Mehdi Ghaeini', photo: 'images/team-mehdi.jpg' },
  { name: 'Ben Shih', photo: 'images/team-ben.jpg' },
  { name: 'Iuliia Dutchak', photo: 'images/team-iuliia.jpg' },
  { name: 'Cyan Xiao', photo: 'images/team-cyan.jpg' },
];
// SAP (Fiori) team, shared across the two SAP projects.
const SAP_TEAM = [
  { name: 'Richard Byrnes', photo: 'images/team-richard.webp' },
  { name: 'Goran Peuc', photo: 'images/team-goran.jpg' },
  { name: 'Colin Doherty', photo: 'images/team-colin.jpg' },
  { name: 'Christine McCarthy', photo: 'images/team-christine.png' },
  { name: 'Aisling Noone', photo: 'images/team-aisling.jpg' },
];
window.PROJECTS['developer-tools'].teamMembers = SAP_TEAM;
window.PROJECTS['design-systems'].teamMembers = SAP_TEAM;

Object.values(window.PROJECTS).forEach((project) => {
  if (!project.teamMembers) project.teamMembers = CORE_TEAM;
});
